package hevc

type HEVCNALUnitType int
type HEVCSliceType int

const (
	HevcNalTrailN       = HEVCNALUnitType(0)
	HevcNalTrailR       = HEVCNALUnitType(1)
	HevcNalTsaN         = HEVCNALUnitType(2)
	HevcNalTsaR         = HEVCNALUnitType(3)
	HevcNalSTSAN        = HEVCNALUnitType(4)
	HevcNalSTSAR        = HEVCNALUnitType(5)
	HevcNalRADLN        = HEVCNALUnitType(6)
	HevcNalRADLR        = HEVCNALUnitType(7)
	HevcNalRASLN        = HEVCNALUnitType(8)
	HevcNalRASLR        = HEVCNALUnitType(9)
	HevcNalVclN10       = HEVCNALUnitType(10)
	HevcNalVclR11       = HEVCNALUnitType(11)
	HevcNalVclN12       = HEVCNALUnitType(12)
	HevcNalVclR13       = HEVCNALUnitType(13)
	HevcNalVclN14       = HEVCNALUnitType(14)
	HevcNalVclR15       = HEVCNALUnitType(15)
	HevcNalBlaWLP       = HEVCNALUnitType(16)
	HevcNalBlaWRADL     = HEVCNALUnitType(17)
	HevcNalBlaNLP       = HEVCNALUnitType(18)
	HevcNalIdrWRADL     = HEVCNALUnitType(19)
	HevcNalIdrNLP       = HEVCNALUnitType(20)
	HevcNalCraNUT       = HEVCNALUnitType(21)
	HevcNalRsvIRAPVCL22 = HEVCNALUnitType(22)
	HevcNalRsvIRAPVCL23 = HEVCNALUnitType(23)
	HevcNalRsvVCL24     = HEVCNALUnitType(24)
	HevcNalRsvVCL25     = HEVCNALUnitType(25)
	HevcNalRsvVCL26     = HEVCNALUnitType(26)
	HevcNalRsvVCL27     = HEVCNALUnitType(27)
	HevcNalRsvVCL28     = HEVCNALUnitType(28)
	HevcNalRsvVCL29     = HEVCNALUnitType(29)
	HevcNalRsvVCL30     = HEVCNALUnitType(30)
	HevcNalRsvVCL31     = HEVCNALUnitType(31)
	HevcNalVPS          = HEVCNALUnitType(32)
	HevcNalSPS          = HEVCNALUnitType(33)
	HevcNalPPS          = HEVCNALUnitType(34)
	HevcNalAUD          = HEVCNALUnitType(35)
	HevcNalEOSNUT       = HEVCNALUnitType(36)
	HevcNalEOBNUT       = HEVCNALUnitType(37)
	HevcNalFDNUT        = HEVCNALUnitType(38)
	HevcNalSeiPPrefix   = HEVCNALUnitType(39)
	HevcNalSeiSuffix    = HEVCNALUnitType(40)
	HevcNalRsvNVCL41    = HEVCNALUnitType(41)
	HevcNalRsvNVCL42    = HEVCNALUnitType(42)
	HevcNalRsvNVCL43    = HEVCNALUnitType(43)
	HevcNalRsvNVCL44    = HEVCNALUnitType(44)
	HevcNalRsvNVCL45    = HEVCNALUnitType(45)
	HevcNalRsvNVCL46    = HEVCNALUnitType(46)
	HevcNalRsvNVCL47    = HEVCNALUnitType(47)
	HevcNalUNSPEC48     = HEVCNALUnitType(48)
	HevcNalUNSPEC49     = HEVCNALUnitType(49)
	HevcNalUNSPEC50     = HEVCNALUnitType(50)
	HevcNalUNSPEC51     = HEVCNALUnitType(51)
	HevcNalUNSPEC52     = HEVCNALUnitType(52)
	HevcNalUNSPEC53     = HEVCNALUnitType(53)
	HevcNalUNSPEC54     = HEVCNALUnitType(54)
	HevcNalUNSPEC55     = HEVCNALUnitType(55)
	HevcNalUNSPEC56     = HEVCNALUnitType(56)
	HevcNalUNSPEC57     = HEVCNALUnitType(57)
	HevcNalUNSPEC58     = HEVCNALUnitType(58)
	HevcNalUNSPEC59     = HEVCNALUnitType(59)
	HevcNalUNSPEC60     = HEVCNALUnitType(60)
	HevcNalUNSPEC61     = HEVCNALUnitType(61)
	HevcNalUNSPEC62     = HEVCNALUnitType(62)
	HevcNalUNSPEC63     = HEVCNALUnitType(63)
)

const (
	HevcSliceB = HEVCSliceType(0)
	HevcSliceP = HEVCSliceType(1)
	HevcSliceI = HEVCSliceType(2)
)
